real_nav_goals:
  Q1:
    position:
      x: -1.581
      y: 0.039
      z: 0.017
    orientation:
      x: 0.002
      y: -0.000
      z: -0.018 
      w: 1.000
  Q2:
    position:
      x: -1.610
      y: -1.159
      z: 0.026
    orientation:
      x: -0.001
      y: -0.003
      z: 0.010
      w: 1.000
  Q3:
    position:
      x: -0.069
      y: -0.976
      z: 0.033
    orientation:
      x: -0.002
      y: 0.003
      z: 1.000
      w: -0.020
  center:
    position:
      x: -0.665
      y: -0.548
      z: 0.019
    orientation:
      x: -0.003
      y: -0.001
      z: -0.601
      w: 0.799
  home:
    position:
      x: 0.045
      y: 0.180
      z: 0.015
    orientation:
      x: 0.002
      y: -0.005
      z: -0.010
      w: 1.000
    