real_nav_goals:
  center1:
    position:
      x: -0.736
      y: 0.169
      z: 0.049
    orientation:
      x: -0.000
      y: 0.002
      z: -0.693
      w: 0.721
  center2:
    position:
      x: -0.670
      y: -0.869
      z: 0.053
    orientation:
      x: -0.004
      y: -0.002
      z: -0.692
      w: 0.722
  home:
    position:
      x: -0.056
      y: 0.216
      z: 0.049
    orientation:
      x: 0.001
      y: -0.006
      z: 0.104
      w: 0.995