real_nav_goals:
  marker:
    position:
      x: -1.126
      y: -0.050
      z: 0.013
    orientation:
      x: 0.001
      y: -0.003
      z: 0.999
      w: -0.043
  atdoor:
    position:
      x: -0.560
      y: -0.152
      z: 0.013
    orientation:
      x: -0.00
      y: 0.001
      z: -0.682
      w: 0.731
  postdoor:
    position:
      x: -0.538
      y: -0.989
      z: 0.004
    orientation:
      x: -0.003
      y: -0.002
      z: -0.728
      w: 0.686
  bin:
    position:
      x: -0.086
      y: -1.155
      z: 0.008
    orientation:
      x: -0.003
      y: -0.006
      z: -0.432
      w: 0.902
  home:
    position:
      x: 0
      y: 0
      z: 0
    orientation:
      x: 0.003
      y: -0.012
      z: -0.000
      w: 1.000
  table:
    position:
      x: -1.125
      y: -0.076
      z: -0.001
    orientation:
      x: 0.001
      y: -0.003
      z: 0.721
      w: 0.693

    